steps:
  - id: "docker-build"
    name: "gcr.io/cloud-builders/docker"
    args: ['build', '-t', 'gcr.io/vibrant-victory-346914/go-microservice','.']

  - id: "docker-push"
    name: "gcr.io/cloud-builders/docker"
    args: ['push', 'gcr.io/vibrant-victory-346914/go-microservice']

  - id: "docker-layer"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        echo "FROM $_IMAGE_NAME
        COPY --from=gcr.io/cloudsql-docker/gce-proxy /cloud_sql_proxy /cloudsql/cloud_sql_proxy" > Dockerfile-proxy;

        docker build -f Dockerfile-proxy -t ${_IMAGE_NAME}-proxy .
        
  # For TCP connections
  - id: "migrate-tcp"
    name: "${_IMAGE_NAME}-proxy"
    dir: go-microservice
    env:
      - "DATABASE_NAME=${_DATABASE_NAME}"
      - "DATABASE_USER=${_DATABASE_USER}"
      - "DATABASE_HOST=127.0.0.1"
      - "DATABASE_PORT=${_DATABASE_PORT}"
      - "DATABASE_TYPE=${_DATABASE_TYPE}"
      - "DATABASE_PASS=${_DATABASE_PASSWORD_KEY}"
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        /cloudsql/cloud_sql_proxy -instances=${_INSTANCE_CONNECTION_NAME}=tcp:${_DATABASE_PORT} & sleep 2;
   
  - id: "migrate-socket"
    name: "${_IMAGE_NAME}-proxy"
    dir: go-microservice
    env:
      - "DATABASE_NAME=${_DATABASE_NAME}"
      - "DATABASE_USER=${_DATABASE_USER}"
      - "INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME}"
      - "DATABASE_TYPE=${_DATABASE_TYPE}"
      - "DATABASE_PASS=${_DATABASE_PASSWORD_KEY}"
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        /cloudsql/cloud_sql_proxy -instances=${_INSTANCE_CONNECTION_NAME} -dir=/cloudsql & sleep 2;
        if [ $_DATABASE_TYPE = 'mssql' ]; then echo "MSSQL doesn't support Unix Sockets. Skippng."; exit 0; fi;

  - id: "deploy-microservice"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ['run', 'deploy','go-microservice', '--image','gcr.io/vibrant-victory-346914/go-microservice', '--region','us-central1', '--add-cloudsql-instances', 'vibrant-victory-346914:us-central1:mypostgres','--set-env-vars','INSTANCE_UNIX_SOCKET='/cloudsql/vibrant-victory-346914:us-central1:mypostgres'','--set-env-vars','DB_USER='postgres'','--set-env-vars','DB_PASS='root'','--set-env-vars','DB_NAME='chicago_business_intelligence'','--platform','managed', '--port','80']
        
options:
  dynamic_substitutions: true

substitutions:
  _DATABASE_USER: postgres
  _DATABASE_NAME: chicago_business_intelligence
  _INSTANCE_CONNECTION_NAME: vibrant-victory-346914:us-central1:mypostgres
  _DATABASE_PORT: '5432'
  _DATABASE_TYPE: postgres
  _DATABASE_PASSWORD_KEY: root
  _IMAGE_NAME: gcr.io/vibrant-victory-346914/go-microservice
