steps:
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/vibrant-victory-346914/go-microservice','.']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/vibrant-victory-346914/go-microservice']
  
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args: ['run', 'deploy','go-microservice', '--image','gcr.io/vibrant-victory-346914/go-microservice', '--region','us-central1', '--platform','managed', '--port','80']
images:
- gcr.io/vibrant-victory-346914/go-microservice

